name: legacy_draggable_dialog
description: "A draggable dialog helper for Flutter. You can use it to create a fully customizable dialog with a draggable header. Stays within the bounds of the screen."
version: 0.0.2
license: MIT
homepage: https://github.com/barneysspeedshop/legacy_draggable_dialog
repository: https://github.com/barneysspeedshop/legacy_draggable_dialog
issue_tracker: https://github.com/barneysspeedshop/legacy_draggable_dialog/issues

topics:
  - draggable
  - dialog

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter: